# Data preprocessing

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import scipy.stats as st
import statsmodels.api as sm
import matplotlib.pyplot as plt
import io
from collections import Counter
from pprint import pprint
import seaborn as sns
from sklearn import preprocessing

/home/sahulphaniraj/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [3]:
CgmData = pd.read_csv('/home/sahulphaniraj/csce633-ml/MachineLearningProject/Dataset/PlosJournalData/RawDataCsv.csv')

In [6]:
a=CgmData['Meal'].unique()

In [7]:
a

array(['PB 1', 'PB 2', 'CF 1', 'CF 2', 'Bar 1', 'Bar 2'], dtype=object)

In [9]:
CgmData['Meal'] = CgmData['Meal'].replace('PB 1','PB')

In [11]:
CgmData['Meal'] = CgmData['Meal'].replace('PB 2','PB')

In [12]:
CgmData['Meal'] = CgmData['Meal'].replace('CF 1','CF')
CgmData['Meal'] = CgmData['Meal'].replace('CF 2','CF')
CgmData['Meal'] = CgmData['Meal'].replace('Bar 1','Bar')
CgmData['Meal'] = CgmData['Meal'].replace('Bar 2','Bar')

In [14]:
CgmData['Meal'].unique()

array(['PB', 'CF', 'Bar'], dtype=object)

In [15]:
MealtoMacro = pd.read_csv('/home/sahulphaniraj/csce633-ml/MachineLearningProject/Dataset/PlosJournalData/MealtoMacronutrient.csv')

In [16]:
MealtoMacro

  Meal_Nutrients  Calories   Fat  Protein  Carb  Sugar  Fiber
0             PB       430  20.0       18    51   12.0   12.0
1            Bar       370  18.0        9    48   19.0    6.0
2             CF       280   2.5       11    54   35.2    3.3

In [17]:
CgmData

     Meal    userID                 time GlucoseValue
0      PB  2133-001   2016-08-04 8:10:00           81
1      PB  2133-001   2016-08-04 8:15:00           78
2      PB  2133-001   2016-08-04 8:20:00           77
3      PB  2133-001   2016-08-04 8:25:00           79
4      PB  2133-001   2016-08-04 8:30:00           81
5      PB  2133-001   2016-08-04 8:35:00           78
6      PB  2133-001   2016-08-04 8:35:00           76
7      PB  2133-001   2016-08-04 8:40:00           77
8      PB  2133-001   2016-08-04 8:45:00           77
9      PB  2133-001   2016-08-04 8:50:00           77
10     PB  2133-001   2016-08-04 8:55:00           84
11     PB  2133-001   2016-08-04 9:05:00           92
12     PB  2133-001   2016-08-04 9:10:00           88
13     PB  2133-001   2016-08-04 9:15:00           84
14     PB  2133-001   2016-08-04 9:20:00           81
15     PB  2133-001   2016-08-04 9:25:00           80
16     PB  2133-001   2016-08-04 9:30:00           82
17     PB  2133-001   2016-08-04 9:35:00           83
18     PB  2133-001   2016-08-04 9:40:00           82
19     PB  2133-001   2016-08-04 9:45:00           83
20     PB  2133-001   2016-08-04 9:50:00           82
21     PB  2133-001   2016-08-04 9:55:00           82
22     PB  2133-001  2016-08-04 10:00:00           82
23     PB  2133-001  2016-08-04 10:05:00           83
24     PB  2133-001  2016-08-04 10:10:00           83
25     PB  2133-001  2016-08-04 10:15:00           83
26     PB  2133-001  2016-08-04 10:20:00           83
27     PB  2133-001  2016-08-04 10:25:00           84
28     PB  2133-001  2016-08-04 10:30:00           84
29     PB  2133-001  2016-08-04 10:35:00           83
...   ...       ...                  ...          ...
6122  Bar  2133-041   2017-07-20 5:40:00           98
6123  Bar  2133-041   2017-07-20 5:45:00          106
6124  Bar  2133-041   2017-07-20 5:50:00          112
6125  Bar  2133-041   2017-07-20 5:55:00          117
6126  Bar  2133-041   2017-07-20 6:00:00          118
6127  Bar  2133-041   2017-07-20 6:05:00          113
6128  Bar  2133-041   2017-07-20 6:10:00          106
6129  Bar  2133-041   2017-07-20 6:15:00           95
6130  Bar  2133-041   2017-07-20 6:20:00           87
6131  Bar  2133-041   2017-07-20 6:25:00           78
6132  Bar  2133-041   2017-07-20 6:30:00           69
6133  Bar  2133-041   2017-07-20 6:35:00           63
6134  Bar  2133-041   2017-07-20 6:40:00           62
6135  Bar  2133-041   2017-07-20 6:45:00           63
6136  Bar  2133-041   2017-07-20 6:50:00           66
6137  Bar  2133-041   2017-07-20 6:55:00           74
6138  Bar  2133-041   2017-07-20 6:55:00           92
6139  Bar  2133-041   2017-07-20 7:00:00           68
6140  Bar  2133-041   2017-07-20 7:05:00           74
6141  Bar  2133-041   2017-07-20 7:10:00           72
6142  Bar  2133-041   2017-07-20 7:15:00           72
6143  Bar  2133-041   2017-07-20 7:20:00           74
6144  Bar  2133-041   2017-07-20 7:25:00           76
6145  Bar  2133-041   2017-07-20 7:30:00           77
6146  Bar  2133-041   2017-07-20 7:35:00           79
6147  Bar  2133-041   2017-07-20 7:40:00           80
6148  Bar  2133-041   2017-07-20 7:45:00           79
6149  Bar  2133-041   2017-07-20 7:50:00           77
6150  Bar  2133-041   2017-07-20 7:55:00           78
6151  Bar  2133-041   2017-07-20 8:00:00           78

[6152 rows x 4 columns]

In [19]:
CgmDataSorted = CgmData.sort_values(['userID','Meal'],ascending=[True,True])

In [23]:
CgmDataSorted = CgmDataSorted.reset_index(drop=True)

In [24]:
CgmDataSorted['GlucoseValue']

     Meal    userID                 time GlucoseValue
0     Bar  2133-001   2016-08-12 7:50:00           92
1     Bar  2133-001   2016-08-12 7:55:00           92
2     Bar  2133-001   2016-08-12 8:00:00           90
3     Bar  2133-001   2016-08-12 8:05:00           89
4     Bar  2133-001   2016-08-12 8:10:00           90
5     Bar  2133-001   2016-08-12 8:10:00           77
6     Bar  2133-001   2016-08-12 8:15:00           81
7     Bar  2133-001   2016-08-12 8:20:00           77
8     Bar  2133-001   2016-08-12 8:25:00           78
9     Bar  2133-001   2016-08-12 8:30:00           79
10    Bar  2133-001   2016-08-12 8:35:00           89
11    Bar  2133-001   2016-08-12 8:40:00          100
12    Bar  2133-001   2016-08-12 8:45:00          108
13    Bar  2133-001   2016-08-12 8:50:00          111
14    Bar  2133-001   2016-08-12 8:55:00          113
15    Bar  2133-001   2016-08-12 9:05:00          116
16    Bar  2133-001   2016-08-12 9:10:00          114
17    Bar  2133-001   2016-08-12 9:15:00          109
18    Bar  2133-001   2016-08-12 9:20:00          103
19    Bar  2133-001   2016-08-12 9:25:00           94
20    Bar  2133-001   2016-08-12 9:30:00           86
21    Bar  2133-001   2016-08-12 9:35:00           81
22    Bar  2133-001   2016-08-12 9:40:00           79
23    Bar  2133-001   2016-08-12 9:45:00           79
24    Bar  2133-001   2016-08-12 9:50:00           77
25    Bar  2133-001   2016-08-12 9:55:00           78
26    Bar  2133-001  2016-08-12 10:00:00           80
27    Bar  2133-001  2016-08-12 10:05:00           82
28    Bar  2133-001  2016-08-12 10:10:00           80
29    Bar  2133-001  2016-08-12 10:15:00           79
...   ...       ...                  ...          ...
6122   PB  2133-041   2017-07-16 5:50:00          132
6123   PB  2133-041   2017-07-16 5:55:00          131
6124   PB  2133-041   2017-07-16 6:00:00          128
6125   PB  2133-041   2017-07-16 6:05:00          127
6126   PB  2133-041   2017-07-16 6:10:00          125
6127   PB  2133-041   2017-07-16 6:15:00          129
6128   PB  2133-041   2017-07-16 6:20:00          138
6129   PB  2133-041   2017-07-16 6:30:00          155
6130   PB  2133-041   2017-07-16 6:40:00          169
6131   PB  2133-041   2017-07-16 6:45:00          172
6132   PB  2133-041   2017-07-16 6:50:00          171
6133   PB  2133-041   2017-07-16 6:55:00          167
6134   PB  2133-041   2017-07-16 7:00:00          161
6135   PB  2133-041   2017-07-16 7:05:00          155
6136   PB  2133-041   2017-07-16 7:10:00          150
6137   PB  2133-041   2017-07-16 7:15:00          147
6138   PB  2133-041   2017-07-16 7:20:00          145
6139   PB  2133-041   2017-07-16 7:25:00          143
6140   PB  2133-041   2017-07-16 7:30:00          140
6141   PB  2133-041   2017-07-16 7:35:00          136
6142   PB  2133-041   2017-07-16 7:40:00          132
6143   PB  2133-041   2017-07-16 7:45:00          129
6144   PB  2133-041   2017-07-16 7:50:00          124
6145   PB  2133-041   2017-07-16 7:55:00          118
6146   PB  2133-041   2017-07-16 8:00:00          117
6147   PB  2133-041   2017-07-16 8:05:00          118
6148   PB  2133-041   2017-07-16 8:10:00          119
6149   PB  2133-041   2017-07-16 8:15:00          120
6150   PB  2133-041   2017-07-16 8:20:00          121
6151   PB  2133-041   2017-07-16 8:30:00          122

[6152 rows x 4 columns]

In [26]:
len(CgmData['userID'].unique())

30

In [36]:
userlist = CgmDataSorted['userID'].unique()
mealist = ['PB','CF','Bar']
for user in range(len(userlist)):
    for meal in range(1):
        username = userlist[user]
        mealname = mealist[meal]
        temp=CgmDataSorted.loc[(CgmDataSorted['userID']==username) & (CgmDataSorted['Meal']==mealname)]
        filename = 'User'+user+'Meal'+meal
        temp.to_csv(filename,sep='\t')

    Meal    userID                 time GlucoseValue
144   PB  2133-001   2016-08-04 8:10:00           81
145   PB  2133-001   2016-08-04 8:15:00           78
146   PB  2133-001   2016-08-04 8:20:00           77
147   PB  2133-001   2016-08-04 8:25:00           79
148   PB  2133-001   2016-08-04 8:30:00           81
149   PB  2133-001   2016-08-04 8:35:00           78
150   PB  2133-001   2016-08-04 8:35:00           76
151   PB  2133-001   2016-08-04 8:40:00           77
152   PB  2133-001   2016-08-04 8:45:00           77
153   PB  2133-001   2016-08-04 8:50:00           77
154   PB  2133-001   2016-08-04 8:55:00           84
155   PB  2133-001   2016-08-04 9:05:00           92
156   PB  2133-001   2016-08-04 9:10:00           88
157   PB  2133-001   2016-08-04 9:15:00           84
158   PB  2133-001   2016-08-04 9:20:00           81
159   PB  2133-001   2016-08-04 9:25:00           80
160   PB  2133-001   2016-08-04 9:30:00           82
161   PB  2133-001   2016-08-04 9:35:00           83
162   PB  2133-001   2016-08-04 9:40:00           82
163   PB  2133-001   2016-08-04 9:45:00           83
164   PB  2133-001   2016-08-04 9:50:00           82
165   PB  2133-001   2016-08-04 9:55:00           82
166   PB  2133-001  2016-08-04 10:00:00           82
167   PB  2133-001  2016-08-04 10:05:00           83
168   PB  2133-001  2016-08-04 10:10:00           83
169   PB  2133-001  2016-08-04 10:15:00           83
170   PB  2133-001  2016-08-04 10:20:00           83
171   PB  2133-001  2016-08-04 10:25:00           84
172   PB  2133-001  2016-08-04 10:30:00           84
173   PB  2133-001  2016-08-04 10:35:00           83
..   ...       ...                  ...          ...
189   PB  2133-001   2016-08-06 9:10:00           73
190   PB  2133-001   2016-08-06 9:15:00           77
191   PB  2133-001   2016-08-06 9:20:00           75
192   PB  2133-001   2016-08-06 9:25:00           75
193   PB  2133-001   2016-08-06 9:30:00           79
194   PB  2133-001   2016-08-06 9:35:00           87
195   PB  2133-001   2016-08-06 9:40:00           87
196   PB  2133-001   2016-08-06 9:45:00           86
197   PB  2133-001   2016-08-06 9:50:00           89
198   PB  2133-001   2016-08-06 9:55:00           93
199   PB  2133-001  2016-08-06 10:00:00           95
200   PB  2133-001  2016-08-06 10:05:00           94
201   PB  2133-001  2016-08-06 10:10:00           92
202   PB  2133-001  2016-08-06 10:15:00           87
203   PB  2133-001  2016-08-06 10:20:00           83
204   PB  2133-001  2016-08-06 10:20:00           83
205   PB  2133-001  2016-08-06 10:25:00           82
206   PB  2133-001  2016-08-06 10:30:00           82
207   PB  2133-001  2016-08-06 10:35:00           83
208   PB  2133-001  2016-08-06 10:40:00           84
209   PB  2133-001  2016-08-06 10:45:00           84
210   PB  2133-001  2016-08-06 10:50:00           79
211   PB  2133-001  2016-08-06 10:55:00           77
212   PB  2133-001  2016-08-06 11:00:00           75
213   PB  2133-001  2016-08-06 11:05:00           76
214   PB  2133-001  2016-08-06 11:10:00           77
215   PB  2133-001  2016-08-06 11:15:00           75
216   PB  2133-001  2016-08-06 11:20:00           76
217   PB  2133-001  2016-08-06 11:25:00           77
218   PB  2133-001  2016-08-06 11:30:00           78

[75 rows x 4 columns]
***************************************
    Meal    userID                 time GlucoseValue
344   PB  2133-002  2016-09-14 11:30:00           96
345   PB  2133-002  2016-09-14 11:35:00           82
346   PB  2133-002  2016-09-14 11:35:00           80
347   PB  2133-002  2016-09-14 11:40:00           79
348   PB  2133-002  2016-09-14 11:45:00           75
349   PB  2133-002  2016-09-14 11:50:00           73
350   PB  2133-002  2016-09-14 11:55:00           75
351   PB  2133-002  2016-09-14 12:00:00           76
352   PB  2133-002  2016-09-14 12:05:00           74
353   PB  2133-002  2016-09-14 12:10:00           76
354   PB  2133-002  2016-09-14 12:15:00           79
355   PB  2133-002  2016-09-14 12:20:00           82
356   PB  2133-002  2016-09-14 12:25:00           91
357   PB  2133-002  2016-09-14 12:30:00           97
358   PB  2133-002  2016-09-14 12:35:00          103
359   PB  2133-002  2016-09-14 12:40:00          107
360   PB  2133-002  2016-09-14 12:45:00          110
361   PB  2133-002  2016-09-14 12:50:00          113
362   PB  2133-002  2016-09-14 12:55:00          114
363   PB  2133-002  2016-09-14 13:00:00          111
364   PB  2133-002  2016-09-14 13:05:00          107
365   PB  2133-002  2016-09-14 13:10:00          106
366   PB  2133-002  2016-09-14 13:15:00          100
367   PB  2133-002  2016-09-14 13:20:00           97
368   PB  2133-002  2016-09-14 13:25:00           96
369   PB  2133-002  2016-09-14 13:30:00           97
370   PB  2133-002  2016-09-14 13:35:00           95
371   PB  2133-002  2016-09-14 13:40:00           96
372   PB  2133-002  2016-09-14 13:45:00           97
373   PB  2133-002  2016-09-14 13:50:00           97
..   ...       ...                  ...          ...
389   PB  2133-002   2016-09-23 8:25:00           74
390   PB  2133-002   2016-09-23 8:30:00           73
391   PB  2133-002   2016-09-23 8:35:00           72
392   PB  2133-002   2016-09-23 8:40:00           73
393   PB  2133-002   2016-09-23 8:45:00           75
394   PB  2133-002   2016-09-23 8:50:00           78
395   PB  2133-002   2016-09-23 8:55:00           81
396   PB  2133-002   2016-09-23 9:00:00           88
397   PB  2133-002   2016-09-23 9:05:00           94
398   PB  2133-002   2016-09-23 9:10:00           99
399   PB  2133-002   2016-09-23 9:15:00          102
400   PB  2133-002   2016-09-23 9:20:00          103
401   PB  2133-002   2016-09-23 9:25:00          102
402   PB  2133-002   2016-09-23 9:30:00          106
403   PB  2133-002   2016-09-23 9:35:00          109
404   PB  2133-002   2016-09-23 9:40:00          109
405   PB  2133-002   2016-09-23 9:45:00          108
406   PB  2133-002   2016-09-23 9:50:00          108
407   PB  2133-002   2016-09-23 9:55:00          109
408   PB  2133-002  2016-09-23 10:00:00          109
409   PB  2133-002  2016-09-23 10:05:00          110
410   PB  2133-002  2016-09-23 10:10:00          110
411   PB  2133-002  2016-09-23 10:15:00          111
412   PB  2133-002  2016-09-23 10:20:00          112
413   PB  2133-002  2016-09-23 10:25:00          113
414   PB  2133-002  2016-09-23 10:30:00          112
415   PB  2133-002  2016-09-23 10:35:00          113
416   PB  2133-002  2016-09-23 10:40:00          112
417   PB  2133-002  2016-09-23 10:45:00          111
418   PB  2133-002  2016-09-23 10:50:00          112

[75 rows x 4 columns]
***************************************

In [13]:
CgmData

     Meal    userID                 time GlucoseValue
0      PB  2133-001   2016-08-04 8:10:00           81
1      PB  2133-001   2016-08-04 8:15:00           78
2      PB  2133-001   2016-08-04 8:20:00           77
3      PB  2133-001   2016-08-04 8:25:00           79
4      PB  2133-001   2016-08-04 8:30:00           81
5      PB  2133-001   2016-08-04 8:35:00           78
6      PB  2133-001   2016-08-04 8:35:00           76
7      PB  2133-001   2016-08-04 8:40:00           77
8      PB  2133-001   2016-08-04 8:45:00           77
9      PB  2133-001   2016-08-04 8:50:00           77
10     PB  2133-001   2016-08-04 8:55:00           84
11     PB  2133-001   2016-08-04 9:05:00           92
12     PB  2133-001   2016-08-04 9:10:00           88
13     PB  2133-001   2016-08-04 9:15:00           84
14     PB  2133-001   2016-08-04 9:20:00           81
15     PB  2133-001   2016-08-04 9:25:00           80
16     PB  2133-001   2016-08-04 9:30:00           82
17     PB  2133-001   2016-08-04 9:35:00           83
18     PB  2133-001   2016-08-04 9:40:00           82
19     PB  2133-001   2016-08-04 9:45:00           83
20     PB  2133-001   2016-08-04 9:50:00           82
21     PB  2133-001   2016-08-04 9:55:00           82
22     PB  2133-001  2016-08-04 10:00:00           82
23     PB  2133-001  2016-08-04 10:05:00           83
24     PB  2133-001  2016-08-04 10:10:00           83
25     PB  2133-001  2016-08-04 10:15:00           83
26     PB  2133-001  2016-08-04 10:20:00           83
27     PB  2133-001  2016-08-04 10:25:00           84
28     PB  2133-001  2016-08-04 10:30:00           84
29     PB  2133-001  2016-08-04 10:35:00           83
...   ...       ...                  ...          ...
6122  Bar  2133-041   2017-07-20 5:40:00           98
6123  Bar  2133-041   2017-07-20 5:45:00          106
6124  Bar  2133-041   2017-07-20 5:50:00          112
6125  Bar  2133-041   2017-07-20 5:55:00          117
6126  Bar  2133-041   2017-07-20 6:00:00          118
6127  Bar  2133-041   2017-07-20 6:05:00          113
6128  Bar  2133-041   2017-07-20 6:10:00          106
6129  Bar  2133-041   2017-07-20 6:15:00           95
6130  Bar  2133-041   2017-07-20 6:20:00           87
6131  Bar  2133-041   2017-07-20 6:25:00           78
6132  Bar  2133-041   2017-07-20 6:30:00           69
6133  Bar  2133-041   2017-07-20 6:35:00           63
6134  Bar  2133-041   2017-07-20 6:40:00           62
6135  Bar  2133-041   2017-07-20 6:45:00           63
6136  Bar  2133-041   2017-07-20 6:50:00           66
6137  Bar  2133-041   2017-07-20 6:55:00           74
6138  Bar  2133-041   2017-07-20 6:55:00           92
6139  Bar  2133-041   2017-07-20 7:00:00           68
6140  Bar  2133-041   2017-07-20 7:05:00           74
6141  Bar  2133-041   2017-07-20 7:10:00           72
6142  Bar  2133-041   2017-07-20 7:15:00           72
6143  Bar  2133-041   2017-07-20 7:20:00           74
6144  Bar  2133-041   2017-07-20 7:25:00           76
6145  Bar  2133-041   2017-07-20 7:30:00           77
6146  Bar  2133-041   2017-07-20 7:35:00           79
6147  Bar  2133-041   2017-07-20 7:40:00           80
6148  Bar  2133-041   2017-07-20 7:45:00           79
6149  Bar  2133-041   2017-07-20 7:50:00           77
6150  Bar  2133-041   2017-07-20 7:55:00           78
6151  Bar  2133-041   2017-07-20 8:00:00           78

[6152 rows x 4 columns]